### ISSUE TITLE
Does not work with the latest version of ipywidgets

### ISSUE THREAD

**Issue by axil** [bokeh/jupyter_bokeh#168]
`jupyter_bokeh` does not work with `ipywidgets >=8.0.0a0` Latest compatible version of ipywidgets is `7.7.2`.

**Comment by axil** [comment]
Here's the relevant migration guide: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/migration_guides.md

Supposedly all that needs to be done is to update `package.json` accordingly.

**Comment by axil** [comment]
Tried to create a reproducible example in a Docker container. Couldn't (although it did appear in two machines, Linux and Windows). Closing as false alarm for the time being.

**Comment by axil** [comment]
Another bunch of tests revealed that the issue is not reproducible on Linux only. It only affects Windows.

**Comment by axil** [comment]
I've found it out why it works on Linux: it is because it uses the global version of the notebook extension and not from the virtualenv. So it is basically the same on Windows and Linux.

Got it working with latest ipywidgets (8.0.2) by manually patching the index.js file (searched and replaced all instances of `pWidget` to `luminoWidget` and `PhosphorWidget` to `LuminoWidget`).

My suggestion is that updating `package.json` as described in the link above should suffice:

```diff
- "@jupyter-widgets/base": "^2 || ^3 || ^4",
+ "@jupyter-widgets/base": "^6",
```

But I can't validate it as jupyter does not recognize the index.js I'm building for some reason (both patched and non-patched). It says: 

```
TypeError: Cannot read properties of undefined (reading 'BokehModel')
    at manager.js:159:13
    at async u.loadModelClass (manager-base.js:572:13)
    at async u._make_model (manager-base.js:410:13)
```
I've tried building with both npm and jlpm. The build log looks clean:

```
~/jupyter_bokeh% npm run build:lib

> @bokeh/jupyter_bokeh@3.0.4 build:lib /home/axil/jupyter_bokeh
> tsc

~/jupyter_bokeh% npm run build:nbextension

> @bokeh/jupyter_bokeh@3.0.4 build:nbextension /home/axil/jupyter_bokeh
> webpack -p

Hash: 0f72852c1636829894e8faad6bccde35b005587c
Version: webpack 4.46.0
Child
    Hash: 0f72852c1636829894e8
    Time: 17243ms
    Built at: 14/09/2022 21:29:33
           Asset      Size  Chunks                          Chunk Names
        index.js   416 KiB       0  [emitted]        [big]  main
    index.js.map  2.08 MiB       0  [emitted] [dev]         main
    Entrypoint main [big] = index.js index.js.map
      [5] ./lib/metadata.js 73 bytes {0} [built]
      [8] (webpack)/buildin/global.js 472 bytes {0} [built]
     [29] (webpack)/buildin/module.js 497 bytes {0} [built]
     [36] crypto (ignored) 15 bytes {0} [built]
    [106] ./node_modules/underscore/modules/index-all.js + 159 modules 81.3 KiB {0} [built]
          |    160 modules
    [107] ./lib/extension.js + 26 modules 784 KiB {0} [built]
          | ./lib/extension.js 433 bytes [built]
          | ./lib/index.js 91 bytes [built]
          | ./lib/widgets.js 7.18 KiB [built]
          | ./lib/plugin.js 1.7 KiB [built]
          | ./lib/manager.js 471 bytes [built]
          | ./lib/renderer.js 4.38 KiB [built]
          |     + 21 hidden modules
        + 102 hidden modules
Child
    Hash: faad6bccde35b005587c
    Time: 16131ms
    Built at: 14/09/2022 21:29:32
           Asset      Size  Chunks                          Chunk Names
        index.js   416 KiB       0  [emitted]        [big]  main
    index.js.map  2.08 MiB       0  [emitted] [dev]         main
    Entrypoint main [big] = index.js index.js.map
      [5] ./lib/metadata.js 73 bytes {0} [built]
      [8] (webpack)/buildin/global.js 472 bytes {0} [built]
     [29] (webpack)/buildin/module.js 497 bytes {0} [built]
     [36] crypto (ignored) 15 bytes {0} [built]
    [106] ./node_modules/underscore/modules/index-all.js + 159 modules 81.3 KiB {0} [built]
          |    160 modules
    [107] ./lib/index.js + 25 modules 784 KiB {0} [built]
          | ./lib/index.js 91 bytes [built]
          | ./lib/widgets.js 7.18 KiB [built]
          | ./lib/plugin.js 1.7 KiB [built]
          | ./lib/manager.js 471 bytes [built]
          | ./lib/renderer.js 4.38 KiB [built]
          |     + 21 hidden modules
        + 102 hidden modules
```
I've tried building both the latest commit in the main branch and the following commit (could not find tag 3.0.4)

```
commit ca623a513ce406a6b06829d032ff063dfb0e3c83 (HEAD -> v3.0.4)
Author: Mateusz Paprocki <mattpap@gmail.com>
Date:   Thu Sep 30 20:01:55 2021 +0200

    Publish version 3.0.4
```

What could possibly be the reason for the above mentioned jupyter error?

**Comment by axil** [comment]
@mattpap I've included the change proposed above into packages.json, built the project, tested against latest ipywigets 8.0.2 (works fine) and generated the package-lock and yarn.lock files.
